server:
  port: 9006
spring:
  application:
    name: tensquare-spit #指定服务名
  data:
    mongodb:
      host: 192.168.32.128
      database: spitdb  # 数据库
    redis:
      host: 192.168.32.128
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG